context:
  name: vllm
  build_number: 0
  version: ${{ build }}
  git_repo: ${{  env.get("PIXI_PROJECT_ROOT") }}

package:
  name: ${{ name }}
  version: ${{ git.latest_tag( git_repo ) }}+dev${{ git.head_rev( git_repo )[:8] }}

source:
  - path: ${{ git_repo }}
    patches:
      # - 01-cmake-setup.patch
      - 02-cmakefiles.patch
    # use_gitignore: false
  - path: ${{ git_repo }}/.git
    target_directory: .git

build:
  number: ${{ build_number }}
  string: py${{ python | version_to_buildstring }}_cuda${{ cuda | version_to_buildstring }}_pt${{ pytorch | replace('.', '') }}_${{ hash }}_${{ build_number }}
  python:
    entry_points:
      - vllm = vllm.entrypoints.cli.main:main
    version_independent: true
  script:
    content:
      - set -ex
      - python use_existing_torch.py
      - |
        export MAX_JOBS=8
        # export NVCC_THREADS=$(($CPU_COUNT / 2 > 16 ? 16 : $CPU_COUNT / 2 ))
      - pip install . -vv
    env:
      CUDA_HOME: $BUILD_PREFIX
      TORCH_CUDA_ARCH_LIST: ${{ TORCH_CUDA_ARCH_LIST }}
      VLLM_FA_CMAKE_GPU_ARCHES: ${{ CMAKE_CUDA_ARCHITECTURES }}
      VERBOSE: "1"

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('cuda') }}
    - ${{ stdlib('c') }}
    - cmake
    - ninja
    - sccache
  host:
    - cuda-libraries-dev =${{ cuda_compiler_version }}
    - cuda-nvml-dev
    - nvtx-c
    - pytorch
    - pytorch *cuda*
    - libtorch
    - python
    - regex
    - pip
    - python-ninja
    - packaging
    - setuptools
    - jinja2
    - setuptools_scm
    - tomcli
  run:
    - psutil
    - einops
    - pytorch *cuda*
    - fsspec
    - transformers
    - msgspec
    - pydantic
    - compressed-tensors
    - gguf
    - cloudpickle
    - mistral-common
    - nccl
    - setuptools
    - py-cpuinfo
    - openai
    - opencv
    - pyzmq
    - blake3
    - uvloop
    - fastapi
    - partial-json-parser
    # - ray-default >=2.9
    - nvidia-ml-py
    - xgrammar
    - python-json-logger
    - scipy
    - outlines
    - numba
    # - torchvision
    # - xformers
    - numba
    - prometheus-fastapi-instrumentator
    - lark
    - depyf
    - setproctitle
tests:
  - python:
      imports:
        - vllm
      pip_check: false
